version: '3'

services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=strapi
  strapi:
    build: .
    ports:
      - 1337:1337
    depends_on:
      - mongo
    environment:
      - PROXY_HOST=$PROXY_HOST
